language: cpp

matrix:
  include:
    - os: linux
      cache:
        directories:
          - /var/cache/apt/archives/*.deb
      compiler: gcc
      sudo: require
      dist: trusty
      services:
        - docker
    - os: osx

env:
  global:
    # DEPLOY_HOST
    - secure: "VfOm4jtFH9STANadoyanpfuvhMDvdNzpWodIcEblz7blY5RqqQc4mZk2KQDQp6yNynY2wKOq1f+za1Rlu+bWPtoWZRhZPGiV3BBiQnJ5J1Ze9nlRqX+SCbdo7pwB1woEIuJ/hcOWw1KO8HS4/ftbRbbOZLxTjIxONQKHN2sjRgsZkZmMT4VN7BZKgzESndNzvTZUVS3WKdiX38Mbp2cWyHolGgRDeh8xS2xlePenMtaEmyNGT+0h8Cj1YWthleFxYxU0fSlWmcRAHM9m0qB5M4jg0B0WawuhiFUYpkW9LJJWkuPfsckiGq+RuJ5Iq+RNfnmt3DMTQoUaQdlFC09qc98HYJ3fuGG5UHCmnKGo/U00KxdDRcRfmZpOMm8y/jnFj0reufc7ioOHGxo3vsIrBbtfzyK4k4Uu+hIkpa8YLp1edjSKMSYMgI0gmG8lv22xGUL+gVAeFKpZ7f6jVMEU7OY061FVbneLiKdcMtrt/NWVdrKVkGrGVi0TJN+/GAYmkpT2awatv5Fy6P4QXrHwqYpsDX/KGQ2DTre3/wVrkvDNobi5gmWfzzR95MTFTfvvYe5pOeixQ4njog5G+c2TwJIEwHxczs72+cdXDVio4g3j5fJP47TpMo7r4HCMDK3+shh55/StBhqZLwASL9xRGcogbCv2tszXx3113UzkJGI="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build-${TRAVIS_OS_NAME}.sh

#after_success:
#  - ls -lh travis-out/*
#  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#  - for filename in travis-out/*; do curl --upload-file $filename https://transfer.sh/$(basename $filename); done

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
